---
extends: default

rules:
  braces:
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  brackets:
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0
  document-end:
    present: false
  indentation:
    spaces: 2
    indent-sequences: true
  line-length:
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-lines:
    type: unix
  quoted-strings:
    quote-type: double
    required: only-when-needed
