---
name: markdownlint-cli
author: Nick Osborn
description: Style checker and lint tool for Markdown/CommonMark files.

inputs:
  config_file:
    description: configuration file (JSON or YAML)
    required: false
  dot:
    description: include files/folders with a dot (for example `.github`)
    required: false
  files:
    description: files, directories, or globs
    required: true
  ignore_files:
    description: files to ignore/exclude
    required: false
  ignore_path:
    description: path to file with ignore pattern(s)
    required: false
  rules:
    description: custom rule files
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: check-circle
  color: purple
