---
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:

name: local-test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./
        with:
          config_file: .markdownlintrc
          files: .
          ignore_files: examples/ignore/*
          rules: examples/rules/custom.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
