# yamllint disable rule:line-length
---
name: Tag Versioning

on:
  release:
    types:
      - published
      - edited

permissions:
  contents: read

concurrency:
  group: versioning

jobs:
  actions-tagger:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@330ddfac760021349fef7ff62b372f2f691c20fb # v2.0.3
